from app.models.user import User
from app.models.vehicle import Vehicle
from app.models.driver import Driver
from app.models.trip import Trip
from app.models.trip_event import TripEvent
from app.models.maintenance_log import MaintenanceLog
from app.models.fuel_log import FuelLog
from app.models.expense import Expense
from app.models.notification import Notification
from app.models.vehicle_health import VehicleHealth
from app.models.audit_log import AuditLog